import { esc, btn, bar, group, tag, money, note, gaugeRow } from '../helpers.js';
import { icon } from '../icons.js';
import { dateLabel } from '../../data/calendar.js';
import { asks } from '../../data/asks.js';
import { mutators } from '../../data/catalog.js';
import { absWeek } from '../../engine/state.js';
import { monthlyBudget } from '../../engine/life.js';
import { t } from '../../i18n/index.js';
export function portalApp(s, ui) {
  const best = s.projects.filter(p => p.kind !== 'thesis').reduce((m, p) => Math.max(m, p.progress), 0);
  const now = absWeek(s);
  const leave = asks.find(a => a.id === 'leave');
  const ms = s.milestones || {};
  const mark = v => v === 'pass' ? '✓' : v === 'conditional' ? '◐' : v === 'retake' || v === 'revisions' ? '↻' : '○';
  const word = v => v ? t(v) : t('pending');
  const audit = `<table class="grid"><tr><th>${t('Milestone')}</th><th>${t('Status')}</th><th>${t('When')}</th></tr><tr><td>${t('Coursework (MS exit at 55)')}</td><td>${Math.round(s.coursework)}/100</td><td>${t('years 1–2')}</td></tr><tr><td>${t('Preliminary examination')}</td><td>${mark(ms.prelim)} ${word(ms.prelim)}</td><td>${dateLabel(ms.prelimMonth ?? 23)}</td></tr><tr><td>${t('Thesis proposal (candidacy)')}</td><td>${mark(ms.proposal)} ${word(ms.proposal)}</td><td>${dateLabel(ms.proposalMonth ?? 44)}</td></tr><tr><td>${t('Dissertation')}</td><td>${ms.thesisStarted ? t(s.projects.find(p => p.kind === 'thesis')?.status || 'Drafting') : t('not started')}</td><td>${t('from {month}', { month: dateLabel(54) })}</td></tr><tr><td>${t('Defense')}</td><td>${mark(ms.defense)} ${ms.defense ? t(ms.defense) : (ms.defenseMonth !== null && ms.defenseMonth !== undefined ? t('scheduled') : t('unscheduled'))}</td><td>${ms.defenseMonth !== null && ms.defenseMonth !== undefined ? dateLabel(ms.defenseMonth) : t('by {month}', { month: dateLabel(71) })}</td></tr></table>`;
  const settled = s.ledger?.month === s.month;
  const budget = settled ? s.ledger : monthlyBudget(s);
  const bills = ['rent', 'food', 'premium', 'fees', 'visa', 'remit', 'other', 'interest'].reduce((sum, key) => sum + (budget[key] || 0), 0);
  const balance = budget.net + (budget.refund || 0) + (budget.support || 0) - bills;
  const financeRows = [[t('Stipend (gross)'), budget.stipend], [t('Withholding'), -budget.tax], [t('Take-home pay'), budget.net],
    [t('Rent'), -budget.rent], [t('Food'), -budget.food], [t('Insurance premium'), -budget.premium],
    ...[[t('Term fees'), 'fees'], [t('Visa and immigration fees'), 'visa'], [t('Sent home'), 'remit'], [t('Card interest'), 'interest']].filter(([, key]) => budget[key]).map(([label, key]) => [label, -budget[key]]),
    [t('Everything else'), -budget.other], ...(budget.refund ? [[t('Tax refund'), budget.refund]] : []), ...(budget.support ? [[t('Hardship support'), budget.support]] : [])];
  const appointment = budget.interning || (s.internship && s.month >= s.internship.start && s.month <= s.internship.end) ? t('Internship') : s.flags.fellow ? t('Fellowship') : s.ta ? t('Teaching assistant') : t('Research assistant');
  const prelimNote = ms.prelim === 'pass' ? t('Preliminary examination passed.')
    : ms.prelim === 'conditional' ? t('Conditional pass: an accepted publication is required by August 2031.')
      : t(ms.prelim === 'retake' ? 'Retake scheduled: {month}.' : 'Scheduled: {month}.', { month: dateLabel(ms.prelimMonth ?? 23) });
  return `<div class="portal-banner">${icon('portal', 28)}<div><b>${esc(s.program.name)}</b><small>${t('STUDENT SELF-SERVICE · PORTAL 4.0b (beta since 2019)')}</small></div><span style="margin-left:auto" class="small">${t('Logged in as {name}', { name: s.player.name })}</span></div><div class="portal-crumbs">${t('Home')} &gt; ${t('Academic records')} &gt; ${t('Progress')} &gt; ${t('Progress (current)')} &gt; ${t('Progress')}</div>
  <div class="cols two"><div>${group(t('Degree audit — milestones'), audit)}${group(t('Preliminary examination'), `${tag(s.program.structure === 'exam' ? t('Exam-focused program') : t('Project-focused program'), 'info')}<p class="small" style="margin-top:6px">${esc(prelimNote)} ${s.program.structure === 'exam' ? t('Coursework and presentation preparation carry more weight.') : t('A strong research project carries more weight.')} ${t('An accepted paper helps; it is not mandatory. Committee support matters.')}</p>${gaugeRow(t('Coursework'), s.coursework)}${gaugeRow(t('Presentation'), s.readiness, 'gold')}${gaugeRow(t('Best project'), best, 'green')}<p class="small muted">${t('Papers accepted')}: ${s.counts.accepted}. ${t('Advisor support')}: ${s.relationship.conflict > 60 ? t('strained') : s.relationship.trust > 65 ? t('supportive') : t('developing')}.</p><div class="row">${btn(t('Practice presentation (−6 Energy)'), 'practice', { cls: 'small', disabled: s.stage !== 'plan' || s.actions.practice })}</div>`)}
  ${group(t('Forms'), `<p class="small muted">${t('Every form generates another form. Choose wisely.')}</p><div class="stack">${btn(t('Leave request (asks your advisor)'), 'ask', { id: 'leave', cls: 'small', disabled: s.stage !== 'plan' || (s.askCooldowns.leave || 0) > now, title: leave?.desc })}${btn(t('Emergency financial support'), 'grant', { cls: 'small', disabled: s.stage !== 'plan' || s.player.stats.money >= 500 || s.flags.emergencyGrant, title: t('Once per run, when funds are below $500') })}${btn(t('Change of advisor (opens LabChat)'), 'open', { app: 'chat', cls: 'small', title: t('There is no form. There is a conversation.') })}</div>`)}</div>
  <div>${group(t('Funding & appointment'), `<p><b>${esc(t(settled ? 'This month’s settled budget' : 'Estimated monthly budget'))}</b> · ${esc(dateLabel(s.month))}</p><table class="grid"><tr><td>${t('Appointment')}</td><td class="num">${appointment}</td></tr>${financeRows.map(([label, value]) => `<tr><td>${esc(label)}</td><td class="num">${money(value)}</td></tr>`).join('')}<tr><td>${t('Balance before debt repayment')}</td><td class="num ${balance < 0 ? 'down' : ''}">${money(balance)}</td></tr></table><p class="small muted">${t(settled ? 'Recorded payroll and recurring bills for this month. Later purchases and medical bills are separate; card repayments move money between cash and debt.' : 'Estimate from current funding, housing, food and insurance. Includes scheduled fees and interest; excludes new medical bills, purchases and changes before payroll.')}</p>${budget.note ? `<p class="small">${esc(budget.note)}</p>` : ''}<div class="row">${btn(t('Open Finance'), 'open', { app: 'life', cls: 'small', attrs: 'data-page="money"' })}</div>`)}
  <div class="portal-notice">ⓘ ${t('If this page contradicts another page, both pages are considered authoritative.')}</div>
  ${group(t('Other paths'), `<p class="small">${t('MS exit: {n}/55 coursework.', { n: Math.round(s.coursework) })}<br>${t('Career preparation: {n}/100', { n: Math.round(s.career) })}${s.flags.industryOffer ? ` · ${t('an industry offer is on file')}` : ''}.</p><p class="small muted">${t('Career focus can open an industry opportunity. A different ending can still be a good one.')}</p>`)}
  ${group(t('This run’s conditions'), `<ul class="small">${s.mutators.map(id => { const mu = mutators.find(x => x.id === id); return `<li><b>${esc(mu?.name || id)}</b> — <span class="muted">${esc(mu?.desc || '')}</span></li>`; }).join('')}</ul>`)}</div></div>`;
}
