import { esc, btn, bar, group, tag, money, note, gaugeRow } from '../helpers.js';
import { icon } from '../icons.js';
import { dateLabel } from '../../data/calendar.js';
import { asks } from '../../data/asks.js';
import { mutators } from '../../data/catalog.js';
import { absWeek } from '../../engine/state.js';
import { paperQuality } from '../../engine/paper.js';
import { t } from '../../i18n/index.js';
export function portalApp(s, ui) {
  const best = s.projects.filter(p => p.kind !== 'thesis').reduce((m, p) => Math.max(m, p.progress), 0);
  const now = absWeek(s);
  const leave = asks.find(a => a.id === 'leave');
  const ms = s.milestones || {};
  const mark = v => v === 'pass' ? '✓' : v === 'conditional' ? '◐' : v === 'retake' || v === 'revisions' ? '↻' : '○';
  const word = v => v ? t(v) : t('pending');
  const audit = `<table class="grid"><tr><th>${t('Milestone')}</th><th>${t('Status')}</th><th>${t('When')}</th></tr><tr><td>${t('Coursework (MS exit at 55)')}</td><td>${Math.round(s.coursework)}/100</td><td>${t('years 1–2')}</td></tr><tr><td>${t('Preliminary examination')}</td><td>${mark(ms.prelim)} ${word(ms.prelim)}</td><td>${dateLabel(ms.prelimMonth ?? 23)}</td></tr><tr><td>${t('Thesis proposal (candidacy)')}</td><td>${mark(ms.proposal)} ${word(ms.proposal)}</td><td>${dateLabel(ms.proposalMonth ?? 44)}</td></tr><tr><td>${t('Dissertation')}</td><td>${ms.thesisStarted ? t(s.projects.find(p => p.kind === 'thesis')?.status || 'Drafting') : t('not started')}</td><td>${t('from {month}', { month: dateLabel(54) })}</td></tr><tr><td>${t('Defense')}</td><td>${mark(ms.defense)} ${ms.defense ? t(ms.defense) : (ms.defenseMonth !== null && ms.defenseMonth !== undefined ? t('scheduled') : t('unscheduled'))}</td><td>${ms.defenseMonth !== null && ms.defenseMonth !== undefined ? dateLabel(ms.defenseMonth) : t('by {month}', { month: dateLabel(71) })}</td></tr></table>`;
  const net = s.program.stipend + (s.flags.raise ? 150 : 0) - s.program.rent - s.housing.rentDelta - 900 - (s.flags.cat ? 60 : 0);
  return `<div class="portal-banner">${icon('portal', 28)}<div><b>${esc(s.program.name)}</b><small>${t('STUDENT SELF-SERVICE · PORTAL 4.0b (beta since 2019)')}</small></div><span style="margin-left:auto" class="small">${t('Logged in as {name}', { name: s.player.name })}</span></div><div class="portal-crumbs">${t('Home')} &gt; ${t('Academic records')} &gt; ${t('Progress')} &gt; ${t('Progress (current)')} &gt; ${t('Progress')}</div>
  <div class="cols two"><div>${group(t('Degree audit — milestones'), audit)}${group(t('Preliminary examination'), `${tag(s.program.structure === 'exam' ? t('Exam-focused program') : t('Project-focused program'), 'info')}<p class="small" style="margin-top:6px">${t('Scheduled August 2030.')} ${s.program.structure === 'exam' ? t('Coursework and presentation preparation carry more weight.') : t('A strong research project carries more weight.')} ${t('An accepted paper helps; it is not mandatory. Committee support matters.')}</p>${gaugeRow(t('Coursework'), s.coursework)}${gaugeRow(t('Presentation'), s.readiness, 'gold')}${gaugeRow(t('Best project'), best, 'green')}<p class="small muted">${t('Papers accepted')}: ${s.counts.accepted}. ${t('Advisor support')}: ${s.relationship.conflict > 60 ? t('strained') : s.relationship.trust > 65 ? t('supportive') : t('developing')}.</p><div class="row">${btn(t('Practice presentation (−6 Energy)'), 'practice', { cls: 'small', disabled: s.stage !== 'plan' || s.actions.practice })}</div>`)}
  ${group(t('Forms'), `<p class="small muted">${t('Every form generates another form. Choose wisely.')}</p><div class="stack">${btn(t('Leave request (asks your advisor)'), 'ask', { id: 'leave', cls: 'small', disabled: s.stage !== 'plan' || (s.askCooldowns.leave || 0) > now, title: leave?.desc })}${btn(t('Emergency financial support'), 'grant', { cls: 'small', disabled: s.stage !== 'plan' || s.player.stats.money >= 500 || s.flags.emergencyGrant, title: t('Once per run, when funds are below $500') })}${btn(t('Change of advisor (opens LabChat)'), 'open', { app: 'chat', cls: 'small', title: t('There is no form. There is a conversation.') })}</div>`)}</div>
  <div>${group(t('Funding & appointment'), `<table class="grid"><tr><td>${t('Appointment')}</td><td class="num">${s.flags.fellow ? t('Fellowship') : s.ta ? t('Teaching assistant') : t('Research assistant')}</td></tr><tr><td>${t('Monthly stipend')}</td><td class="num">${money(s.program.stipend + (s.flags.raise ? 150 : 0))}</td></tr><tr><td>${t('Rent')}</td><td class="num">${money(s.program.rent + s.housing.rentDelta)}</td></tr><tr><td>${t('Living expenses')}</td><td class="num">${money(900 + (s.flags.cat ? 60 : 0))}</td></tr><tr><td>${t('Net per month')}</td><td class="num ${net < 0 ? 'down' : ''}">${money(net)}</td></tr><tr><td>${t('Registration')}</td><td class="num">${t('Active (hold pending)')}</td></tr></table>`)}
  <div class="portal-notice">ⓘ ${t('If this page contradicts another page, both pages are considered authoritative.')}</div>
  ${group(t('Other paths'), `<p class="small">${t('MS exit: {n}/55 coursework.', { n: Math.round(s.coursework) })}<br>${t('Career preparation: {n}/100', { n: Math.round(s.career) })}${s.flags.industryOffer ? ` · ${t('an industry offer is on file')}` : ''}.</p><p class="small muted">${t('Career focus can open an industry opportunity. A different ending can still be a good one.')}</p>`)}
  ${group(t('This run’s conditions'), `<ul class="small">${s.mutators.map(id => { const mu = mutators.find(x => x.id === id); return `<li><b>${esc(mu?.name || id)}</b> — <span class="muted">${esc(mu?.desc || '')}</span></li>`; }).join('')}</ul>`)}</div></div>`;
}
