import { test, expect } from '@playwright/test';

for (const lang of ['en', 'zh']) test(`submitting midweek restores meaningful plans without restoring spent time (${lang})`, async ({ page }) => {
  await page.setViewportSize({ width: lang === 'zh' ? 320 : 1440, height: 900 });
  await page.goto('/');
  await page.evaluate(async lang => {
    const { createRun } = await import('/src/engine/state.js');
    const { dispatch } = await import('/src/engine/game.js');
    const { crunchSnapshot } = await import('/src/engine/time.js');
    const { saveRun, emptyMeta } = await import('/src/engine/save.js');
    const { venues } = await import('/src/data/venues.js');
    let s = createRun(4242, { background: 'masters', topic: 'ml', international: false });
    const a = s.advisors[0];
    s.phase = 'admissions'; s.offers = [a.schoolId];
    s.applications = [{ schoolId: a.schoolId, poiId: a.id, status: 'admitted', funding: 'RA' }];
    s = dispatch(s, { type: 'ENROLL', id: a.id });
    s.stage = 'plan'; s.event = null; s.eventQueue = []; s.scheduled = []; s.needsBegin = false;
    s = dispatch(s, { type: 'START_PROJECT' });
    s.month = 4; s.week = 3; s.dayIndex = 2;
    const p = s.projects.find(x => x.id === s.activeProjectId), v = venues.find(x => x.real === 'ICML');
    Object.assign(p, { status: 'Ready', draft: 90, progress: 80, targetMonth: 4, targetVenueId: v.id,
      targetVenue: v.name, venueId: v.id, wizardStep: 4, approvedWithout: true });
    s.crunch = crunchSnapshot(s); s.tempo = 'day'; s.dayMode = s.month; s.focus = null;
    s.player.stats.energy = 80;
    const meta = emptyMeta();
    Object.assign(meta.settings, { lang, quiet: true, tips: false, textSize: 2, selfPaced: true, untimedChoices: true });
    saveRun(localStorage, s, meta);
  }, lang);
  await page.reload();
  await page.locator('.boot').click();
  await page.locator('[data-action="wiz-choice"][data-id="continue"]').click();
  await page.locator('[data-action="wiz-next"]').click();
  await page.locator('.desk-icon[data-app="browser"]').click();
  await expect(page.locator('#typing-zone')).not.toContainText('35%');
  await expect(page.locator('.pipeline')).toContainText(lang === 'zh' ? '已跳过导师审阅' : 'Advisor review skipped');
  await page.locator('.tabs [data-action="browser-tab"][data-id="openregret"]').click();
  await page.locator('[data-action="submit"]').click();
  await page.locator('.desk-icon[data-app="dashboard"]').click();
  await expect(page.locator('.topstrip')).toContainText(lang === 'zh' ? '本月剩余的 3 个工作日' : 'remaining 3 working day(s)');
  await expect(page.locator('.topstrip')).not.toContainText('ICMLater');
  await expect(page.locator('.next-step')).toContainText(lang === 'zh' ? '论文在审期间' : 'While the paper is under review');
  const coursework = page.locator('[data-action="plan"][data-id="coursework"]');
  await expect(coursework).toBeEnabled();
  const unavailable = page.locator('.unavailable-plans');
  await expect(unavailable.locator('summary')).toContainText(lang === 'zh' ? '科研' : 'Research');
  await expect(unavailable.locator('.unavailable-reason')).toBeHidden();
  await unavailable.locator('summary').focus();
  await page.keyboard.press('Enter');
  await expect(unavailable.locator('.unavailable-reason')).toHaveCount(1);
  await expect(unavailable.locator('.unavailable-reason')).toBeVisible();
  await coursework.click();
  await expect(page.locator('.topstrip [data-action="continue"]')).toBeEnabled();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('phdsim.academic-os.v2')).run);
  expect([saved.month, saved.week, saved.dayIndex, saved.tempo]).toEqual([4, 3, 2, 'month']);
  expect(saved.projects.find(p => p.status === 'Submitted')?.draft).toBe(90);
  await page.locator('.next-step [data-action="start-project"]').click();
  await expect(page.locator('[data-action="plan"][data-id="research"]')).toBeEnabled();
  await expect(page.locator('.unavailable-plans')).toHaveCount(0);
  expect(await page.locator('.topstrip').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
});
